### ISSUE TITLE
feature: ability to comment visually selected text

### ISSUE THREAD

**Issue by dhananjaylatkar** [folke/ts-comments.nvim#15]
### Did you check the docs?

- [X] I have read all the ts-comments.nvim docs

### Is your feature request related to a problem? Please describe.

When I visually select text and press `gc` it comments whole line.

e.g. 

```c
static int fun() {}
```
If I select `static` in above code and press `gc` whole line is commented, resulting in -
```c
// static int fun() {}
```

### Describe the solution you'd like

```c
static int fun() {}
```
If I select `static` in above code and press `gc` only selected part should be commented, resulting in -
```c
/* static */ int fun() {}
```

### Describe alternatives you've considered

"numToStr/Comment.nvim" has this behavior

**Comment by folke** [comment]
`ts-comments.nvim` is an enhancement to Neovim's native comments.
Those are linewise only
