### ISSUE TITLE
feature: block comments

### ISSUE THREAD

**Issue by nipunlakshank** [folke/ts-comments.nvim#17]
### Did you check the docs?

- [X] I have read all the ts-comments.nvim docs

### Is your feature request related to a problem? Please describe.

I miss the block comment feature from [previous plugin](https://github.com/numToStr/Comment.nvim) I used.

### Describe the solution you'd like

* Implement a function to comment/uncomment as a block
* Change setup opts table to accept values for both line comments and block comments for each language
* Default keymap suggestion:
  - mode n: gbc
  - mode v: gb

### Describe alternatives you've considered

Change api to add user defined hooks to comment as a block for each language (and a default one to all files)

**Comment by folke** [comment]
The goal of `ts-comments.nvim` is to enhance the native commenting feature of Neovim >= 0.10.
Neovim only supports linewise comments.
Adding block-wise comments is out of scope for this plugin.
