### ISSUE TITLE
How do I set up this plugin for Comment.nvim? 

### ISSUE THREAD

**Issue by 0xN1nja** [folke/ts-comments.nvim#31]
Currently, I am using [JoosepAlviste/nvim-ts-context-commentstring](https://github.com/JoosepAlviste/nvim-ts-context-commentstring), for which I am setting up with [Comment.nvim](https://github.com/numToStr/Comment.nvim) like this:

```lua
"numToStr/Comment.nvim",
event = { "BufReadPre", "BufNewFile" },
opts = function()
	return {
		pre_hook = require("ts_context_commentstring.integrations.comment_nvim").create_pre_hook(),
	}
end,
```

But I am not able to understand how to set up your plugin? There isn't anything related to it in the README.

This part from the README:

```lua
{
  "folke/ts-comments.nvim",
  opts = {},
  event = "VeryLazy",
  enabled = vim.fn.has("nvim-0.10.0") == 1,
}
```

I tried using it, but it didn't work.

**Comment by folke** [comment]
You don't.

`ts-comments.nvim` is only meant to be used with Neovim's native comments, nothing else.
That's pretty clearly stated in the readme.

**Comment by 0xN1nja** [comment]
Oh, sorry. I missed that 😅
