### ISSUE TITLE
Question: Force a commentstring for filetype?

### ISSUE THREAD

**Issue by eirabben** [folke/ts-comments.nvim#35]
Is there any way to force a filetype to use a certain commentstring, even though there are different TS languages inside the file?

An example is a twig file, like this:

```
{% for item in items %}
  <div>
    {{ item.title }}
  </div>
{% endfor %}
```

In this case I would always want a twig style comment (`{# %s #}`), even if commenting the html parts.

**Comment by folke** [comment]
First of all, please use discussions for user questions next time.
Adding the commentstring to lang with ft shoyld wok
