### ISSUE TITLE
bug: Uncommenting in PHP fails if TS parsers `php` and `phpdoc` are installed

### ISSUE THREAD

**Issue by ybc37** [folke/ts-comments.nvim#55]
### Did you check docs and existing issues?

- [X] I have read all the ts-comments.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of ts-comments.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.1

### Operating system/version

Linux 6.10.3-arch1-2

### Describe the bug

First, I'm not actually sure where this bug belongs, because I don't quite understand every part of it.

I noticed, that uncommenting a line in PHP sometimes results in commenting the commented code with block style comments:

1. `$foo = 1;`
2. Comment with `gcc`: `// $foo = 1;`
3. Uncomment with `gcc`: `/*// $foo = 1;*/`

This happens when...
* ...the TS parsers `php` and `phpdoc` are installed
* ...TS highlighting is enabled
* ...the cursor is in the comment while uncommenting (when the cursor is on whitespace before `// ...`, it works as expected).

I can imagine, it's expected behavior somehow, but practically it's unintuitive at best. I wonder if this is something `ts-comments.nvim` can fix/improve or if there's some other approach to change this behavior.

### Steps To Reproduce

Example PHP file (`repro.php`):

```php
<?php

class Foo
{
    private $bar = "";
}
```

1. `nvim -u repro.lua repro.php`
2. `/priv<CR>gcc` -> line is commented; cursor is on the first slash of `// private...`
3. `gcc` -> line is now wrapped with a blockwise comment
4. `u`ndo -> cursor is on the first slash, again
5. `0gcc` -> line is uncommented

### Expected Behavior

The code is uncommented.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/ts-comments.nvim", opts = {} },
    {
      'nvim-treesitter/nvim-treesitter',
      build = ':TSUpdate',
      config = function()
        require('nvim-treesitter.configs').setup({
          ensure_installed = {'php', 'phpdoc'},
          highlight = {
            enable = true,
          },
      })
      end
    },
  }
})
```

**Comment by mauchchhash** [comment]
Happening to me too 😿
